// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SoundUp;

#nullable disable

namespace SoundUp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BaseUserMusic", b =>
                {
                    b.Property<Guid>("FavoritesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WhoFavoritedId")
                        .HasColumnType("uuid");

                    b.HasKey("FavoritesId", "WhoFavoritedId");

                    b.HasIndex("WhoFavoritedId");

                    b.ToTable("BaseUserMusic");
                });

            modelBuilder.Entity("ListenHistoryMusic", b =>
                {
                    b.Property<Guid>("ListenHistoriesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MusicHistoryId")
                        .HasColumnType("uuid");

                    b.HasKey("ListenHistoriesId", "MusicHistoryId");

                    b.HasIndex("MusicHistoryId");

                    b.ToTable("ListenHistoryMusic");
                });

            modelBuilder.Entity("MusicPlaylist", b =>
                {
                    b.Property<Guid>("MusicInPlaylistsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MusicListId")
                        .HasColumnType("uuid");

                    b.HasKey("MusicInPlaylistsId", "MusicListId");

                    b.HasIndex("MusicListId");

                    b.ToTable("MusicPlaylist");
                });

            modelBuilder.Entity("SoundUp.Models.Album", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("SoundUp.Models.BaseUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ListenHistoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.HasKey("Id");

                    b.HasIndex("ListenHistoryId")
                        .IsUnique();

                    b.ToTable("AllUsers");

                    b.HasDiscriminator<string>("UserType").HasValue("BaseUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SoundUp.Models.ListenHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("ListenHistory");
                });

            modelBuilder.Entity("SoundUp.Models.Music", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MusicAudioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("AuthorId");

                    b.ToTable("Music");
                });

            modelBuilder.Entity("SoundUp.Models.MusicAudio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Audio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MusicId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MusicId")
                        .IsUnique();

                    b.ToTable("MusicAudio");
                });

            modelBuilder.Entity("SoundUp.Models.Playlist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.ToTable("PlayLists");
                });

            modelBuilder.Entity("SoundUp.Models.User", b =>
                {
                    b.HasBaseType("SoundUp.Models.BaseUser");

                    b.HasDiscriminator().HasValue("DefaultUser");
                });

            modelBuilder.Entity("SoundUp.Models.UserAuthor", b =>
                {
                    b.HasBaseType("SoundUp.Models.BaseUser");

                    b.HasDiscriminator().HasValue("AuthorForMusic");
                });

            modelBuilder.Entity("BaseUserMusic", b =>
                {
                    b.HasOne("SoundUp.Models.Music", null)
                        .WithMany()
                        .HasForeignKey("FavoritesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoundUp.Models.BaseUser", null)
                        .WithMany()
                        .HasForeignKey("WhoFavoritedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ListenHistoryMusic", b =>
                {
                    b.HasOne("SoundUp.Models.ListenHistory", null)
                        .WithMany()
                        .HasForeignKey("ListenHistoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoundUp.Models.Music", null)
                        .WithMany()
                        .HasForeignKey("MusicHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MusicPlaylist", b =>
                {
                    b.HasOne("SoundUp.Models.Playlist", null)
                        .WithMany()
                        .HasForeignKey("MusicInPlaylistsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoundUp.Models.Music", null)
                        .WithMany()
                        .HasForeignKey("MusicListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SoundUp.Models.Album", b =>
                {
                    b.HasOne("SoundUp.Models.UserAuthor", "Author")
                        .WithMany("Albums")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("SoundUp.Models.BaseUser", b =>
                {
                    b.HasOne("SoundUp.Models.ListenHistory", "ListenHistory")
                        .WithOne("User")
                        .HasForeignKey("SoundUp.Models.BaseUser", "ListenHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ListenHistory");
                });

            modelBuilder.Entity("SoundUp.Models.Music", b =>
                {
                    b.HasOne("SoundUp.Models.Album", "Album")
                        .WithMany("AlbumMusic")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoundUp.Models.UserAuthor", "Author")
                        .WithMany("CreatedMusics")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("SoundUp.Models.MusicAudio", b =>
                {
                    b.HasOne("SoundUp.Models.Music", "Music")
                        .WithOne("MusicAudio")
                        .HasForeignKey("SoundUp.Models.MusicAudio", "MusicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Music");
                });

            modelBuilder.Entity("SoundUp.Models.Playlist", b =>
                {
                    b.HasOne("SoundUp.Models.BaseUser", "Creator")
                        .WithMany("Playlists")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("SoundUp.Models.Album", b =>
                {
                    b.Navigation("AlbumMusic");
                });

            modelBuilder.Entity("SoundUp.Models.BaseUser", b =>
                {
                    b.Navigation("Playlists");
                });

            modelBuilder.Entity("SoundUp.Models.ListenHistory", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("SoundUp.Models.Music", b =>
                {
                    b.Navigation("MusicAudio");
                });

            modelBuilder.Entity("SoundUp.Models.UserAuthor", b =>
                {
                    b.Navigation("Albums");

                    b.Navigation("CreatedMusics");
                });
#pragma warning restore 612, 618
        }
    }
}
